apiVersion: skaffold/v3alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: chamathjayasekarahtwondevops/auth
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"

    - image: chamathjayasekarahtwondevops/notification
      context: notification-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"

    - image: chamathjayasekarahtwondevops/product
      context: product-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"

    - image: chamathjayasekarahtwondevops/order
      context: order-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: chamathjayasekarahtwondevops/review
      context: review-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: chamathjayasekarahtwondevops/shopping-cart
      context: shopping-cart-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: chamathjayasekarahtwondevops/payment
      context: payment-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: chamathjayasekarahtwondevops/delivery
      context: delivery-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: chamathjayasekarahtwondevops/commission
      context: commission-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"                                

manifests:
  rawYaml:
    - ./config/k8s/*
