apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: chamathjayasekarahtwondevops/delivery
          ports:
            - containerPort: 3009
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery
  type: ClusterIP
  ports:
    - name: delivery
      port: 3009
      targetPort: 3009
