apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: chamathjayasekarahtwondevops/notification
          ports:
            - containerPort: 3002  
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  type: ClusterIP
  ports:
    - name: notification
      port: 3002
      targetPort: 3002
