apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: chamathjayasekarahtwondevops/shopping-cart
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  selector:
    app: shopping-cart
  type: ClusterIP
  ports:
    - name: shopping-cart
      port: 3005
      targetPort: 3005
